name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
     
      - name: Install Hunspell
        run: |
           sudo apt-get update
           sudo apt-get install hunspell
           
      - name: Run cd scripts; make -k VERBOSE=1
        run: cd scripts; make -k VERBOSE=1

      - name: Run cd ..
        run: cd ..
